CREATE TABLE ONBOARDING_CONFIGURATIONS(
    FEATURE_ID VARCHAR(70),
    TENANT_ID VARCHAR(70),
    CONFIGURATION LONGVARCHAR,
    PRIMARY KEY (FEATURE_ID, TENANT_ID)
);

CREATE TABLE TURNSTILES(
    ID VARCHAR(70),
    TENANT_ID VARCHAR(70),
    TENANT_DESCRIPTION VARCHAR(100),
    LOCATION_LATITUDE NUMERIC,
    LOCATION_LONGITUDE NUMERIC,
    STATE VARCHAR(70),
    PRIMARY KEY (ID, TENANT_ID)
);