CREATE TABLE FEATURES(
    FEATURE_ID VARCHAR(70),
    IS_ENABLED INTEGER,
    PRIMARY KEY (FEATURE_ID)
);

CREATE TABLE TENANTS(
    TENANT_ID VARCHAR(70),
    FEATURE_ID VARCHAR(70),
    TENANT_ROLE VARCHAR(50),
    PRIMARY KEY (TENANT_ID, FEATURE_ID),
    FOREIGN KEY (FEATURE_ID) REFERENCES FEATURES(FEATURE_ID)
);